# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f2a188797df3413f65eb318ce4fea2f1227f913bb94b0d252e8e3c656ca892698d9521e00b9872da0c4183832edc9775f785fcc4be3ef06cc778817a76f03c6

test:
  secret_key_base: 0a809f7caedf26ed68a7fd8786b19cdd9959893f3d6303eee6c7a8cd6fecc4f5e8929fec45365cfa04411301a747680f2651704ffee1b6ed5a7480205e49d780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
